### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Max66888** [bottiger1/mscript#1]
When I compile, the following error is reported

//// random_map.sp
//
// random_map.sp(35) : error 017: undefined symbol "SetVariantInt"
// random_map.sp(36) : error 017: undefined symbol "AcceptEntityInput"
// random_map.sp(42) : warning 219: local variable "name" shadows a variable at a preceding level
// random_map.sp(44) : error 017: undefined symbol "FindEntityByClassname"
// random_map.sp(49) : error 017: undefined symbol "SDKHook"
// random_map.sp(58) : error 017: undefined symbol "TF2_AddCondition"
//
// 5 Errors.
//
// Compilation Time: 0.14 sec

I don't know what I did wrong. I didn't compile directly without any settings

**Comment by bottiger1** [comment]
I've fixed the example so it compiles. They were copy and pasted from a real map plugin so some portions were missing.
